# Generated by Django 5.2 on 2025-07-23 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisonnier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero_dossier', models.CharField(max_length=50, unique=True)),
                ('date_incarceration', models.DateField()),
                ('date_liberation', models.DateField(blank=True, null=True)),
                ('infraction', models.TextField()),
                ('centre_detention', models.CharField(max_length=100)),
                ('statut_medical', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('remarque', models.TextField(blank=True)),
                ('prisonnier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.prisonnier')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('diagnostic', models.TextField()),
                ('traitement', models.TextField()),
                ('prisonnier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prison.prisonnier')),
            ],
        ),
    ]
