# Generated by Django 5.2 on 2025-07-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(choices=[('01', 'Janvier'), ('02', 'Février'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Août'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], max_length=2)),
                ('année', models.PositiveIntegerField()),
                ('nombre_dossiers_ouverts', models.PositiveIntegerField()),
                ('nombre_prisonniers_admis', models.PositiveIntegerField()),
                ('nombre_rendez_vous', models.PositiveIntegerField()),
            ],
        ),
    ]
